M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu22.04.1} date Thu 14 Nov 2024 09:30:32 AM EET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-14T09:30:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.950
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X3.128Y17.526
X5.628Y17.526
X8.128Y17.526
T2
X15.28Y17.526
X17.78Y17.526
T3
X3.81Y3.556
T0
M30
